project:
  type: book
  output-dir: docs

website:
  sidebar:
    style: "floating"
    search: true
    contents: auto

book:
  title: "Modélisation des données biologiques avec R"
  reader-mode: true
  
  page-footer:
    left: |
      Modélisation des données biologiques avec R écris par Anicet Ebou
  author: "Anicet Ebou"
  site-url: https://ebedthan.github.io/mbdr/
  repo-url: https://github.com/Ebedthan/mbdr/
  repo-branch: main
  chapters:
    - index.qmd
    - intro.qmd
    - datasets.qmd
    - organigram.qmd
    - exploration.qmd
    - regression.qmd
    - additive.qmd
    - glm.qmd
    - gam.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    author-meta: "Anicet Ebou"
    callout-appearance: simple

editor: visual

